server {
    listen 80;
    listen [::]:80;
    server_name kun.588007.xyz;
    return 301 https://kun.588007.xyz$request_uri;
}

server {
    listen 443 ssl http2;
    listen [::]:443 ssl http2;
    server_name kun.588007.xyz;
    ssl_certificate /hoem/wwwroot/kunpanel/ssl/kun.588007.xyz.crt;
    ssl_certificate_key /hoem/wwwroot/kunpanel/ssl/kun.588007.xyz.key;
    ssl_protocols TLSv1.2 TLSv1.3;
    client_max_body_size 512m;
    access_log /var/log/nginx/kunpanel.access.log;
    error_log /var/log/nginx/kunpanel.error.log;
    location / {
        proxy_pass http://127.0.0.1:18088;
        proxy_http_version 1.1;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $remote_addr;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
        proxy_read_timeout 120s;
        proxy_buffering off;
    }
}
